### ISSUE TITLE
React hooks for UXM

### ISSUE THREAD

**Issue by denar90** [treosh/uxm#4]
wdyt if there will be a bunch of react hooks for UXM?

**Comment by alekseykulikov** [comment]
It would be a nice way to track SPA interactions (#1). uxm is a JS library so that it may be an idea for uxm-react module.

**Comment by denar90** [comment]
>uxm is a JS library so that it may be an idea for uxm-react module.

yup, smth like https://github.com/rehooks but encapsulated in one module, with tree shaking support, etc.

> Encapsulated in one module, I mean that there will be a bunch of hooks in separate files.

In rehooks there are pretty nice template https://github.com/rehooks/template, which can be basic or just reused for uxm-react-hooks module.

**Comment by alekseykulikov** [comment]
inactive, probably, should not be in the core.
